add_header Access-Control-Allow-Origin  $cors_origin always;
add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
add_header Access-Control-Allow-Headers "Range, If-Range, Origin, Accept, Content-Type" always;
add_header Access-Control-Expose-Headers "Content-Length, Content-Range, Accept-Ranges, ETag" always;
add_header Access-Control-Max-Age 86400 always;
add_header Vary "Origin" always;
